name: quavoapp
description: A new Flutter project.
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  flex_color_scheme: ^8.0.0
  flutter_animate: ^4.5.0
  shimmer: ^3.0.0
  iconly: ^1.0.1
  navigation_view: ^1.0.5
  confetti: ^0.7.0
  audioplayers: ^6.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  provider: ^6.1.1
  flutter_lints: ^4.0.0
  google_fonts: ^6.2.1

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/music/
